//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HHH
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Виды стр.
    /// </summary>
    // *** Start programmer edit section *** (ВидыСтр CustomAttributes)

    // *** End programmer edit section *** (ВидыСтр CustomAttributes)
    public enum ВидыСтр
    {
        
        // *** Start programmer edit section *** (ВидыСтр.Имущество CustomAttributes)

        // *** End programmer edit section *** (ВидыСтр.Имущество CustomAttributes)
        [Caption("Имущество")]
        Имущество,
        
        // *** Start programmer edit section *** (ВидыСтр.Жизнь CustomAttributes)

        // *** End programmer edit section *** (ВидыСтр.Жизнь CustomAttributes)
        [Caption("Жизнь")]
        Жизнь,
        
        // *** Start programmer edit section *** (ВидыСтр.ТранспИм CustomAttributes)

        // *** End programmer edit section *** (ВидыСтр.ТранспИм CustomAttributes)
        [Caption("ТранспИм")]
        ТранспИм,
    }
}
