//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HHH
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Договор стр.
    /// </summary>
    // *** Start programmer edit section *** (ДоговорСтр CustomAttributes)

    // *** End programmer edit section *** (ДоговорСтр CustomAttributes)
    [AutoAltered()]
    [Caption("Договор стр")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДоговорСтрE", new string[] {
            "СтрСлучаи as \'Стр случаи\'",
            "Дата as \'Дата\'",
            "СтрПремия as \'Стр премия\'",
            "Номер as \'Номер\'",
            "Клиент as \'Клиент\'",
            "Клиент.ФИО as \'ФИО\'",
            "ПердстЭксп as \'Пердст эксп\'",
            "ПердстЭксп.ОсновПровед as \'Основ провед\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Клиент.ФИО",
            "ПердстЭксп.ОсновПровед",
            "Сотрудники.ФИО"})]
    [MasterViewDefineAttribute("ДоговорСтрE", "Клиент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ДоговорСтрE", "ПердстЭксп", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ОсновПровед")]
    [MasterViewDefineAttribute("ДоговорСтрE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ДоговорСтрL", new string[] {
            "СтрСлучаи as \'Стр случаи\'",
            "Дата as \'Дата\'",
            "СтрПремия as \'Стр премия\'",
            "Номер as \'Номер\'",
            "Клиент.ФИО as \'ФИО\'",
            "ПердстЭксп.ОсновПровед as \'Основ провед\'",
            "Сотрудники.ФИО as \'ФИО\'"})]
    public class ДоговорСтр : ICSSoft.STORMNET.DataObject
    {
        
        private string fСтрСлучаи;
        
        private System.DateTime fДата;
        
        private int fСтрПремия;
        
        private int fНомер;
        
        private IIS.HHH.Клиент fКлиент;
        
        private IIS.HHH.ПердстЭксп fПердстЭксп;
        
        private IIS.HHH.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (ДоговорСтр CustomMembers)

        // *** End programmer edit section *** (ДоговорСтр CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ДоговорСтр.Дата CustomAttributes)

        // *** End programmer edit section *** (ДоговорСтр.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ДоговорСтр.Дата Get start)

                // *** End programmer edit section *** (ДоговорСтр.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ДоговорСтр.Дата Get end)

                // *** End programmer edit section *** (ДоговорСтр.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДоговорСтр.Дата Set start)

                // *** End programmer edit section *** (ДоговорСтр.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ДоговорСтр.Дата Set end)

                // *** End programmer edit section *** (ДоговорСтр.Дата Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ДоговорСтр.Номер CustomAttributes)

        // *** End programmer edit section *** (ДоговорСтр.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ДоговорСтр.Номер Get start)

                // *** End programmer edit section *** (ДоговорСтр.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ДоговорСтр.Номер Get end)

                // *** End programmer edit section *** (ДоговорСтр.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДоговорСтр.Номер Set start)

                // *** End programmer edit section *** (ДоговорСтр.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ДоговорСтр.Номер Set end)

                // *** End programmer edit section *** (ДоговорСтр.Номер Set end)
            }
        }
        
        /// <summary>
        /// СтрПремия.
        /// </summary>
        // *** Start programmer edit section *** (ДоговорСтр.СтрПремия CustomAttributes)

        // *** End programmer edit section *** (ДоговорСтр.СтрПремия CustomAttributes)
        public virtual int СтрПремия
        {
            get
            {
                // *** Start programmer edit section *** (ДоговорСтр.СтрПремия Get start)

                // *** End programmer edit section *** (ДоговорСтр.СтрПремия Get start)
                int result = this.fСтрПремия;
                // *** Start programmer edit section *** (ДоговорСтр.СтрПремия Get end)

                // *** End programmer edit section *** (ДоговорСтр.СтрПремия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДоговорСтр.СтрПремия Set start)

                // *** End programmer edit section *** (ДоговорСтр.СтрПремия Set start)
                this.fСтрПремия = value;
                // *** Start programmer edit section *** (ДоговорСтр.СтрПремия Set end)

                // *** End programmer edit section *** (ДоговорСтр.СтрПремия Set end)
            }
        }
        
        /// <summary>
        /// СтрСлучаи.
        /// </summary>
        // *** Start programmer edit section *** (ДоговорСтр.СтрСлучаи CustomAttributes)

        // *** End programmer edit section *** (ДоговорСтр.СтрСлучаи CustomAttributes)
        [StrLen(255)]
        public virtual string СтрСлучаи
        {
            get
            {
                // *** Start programmer edit section *** (ДоговорСтр.СтрСлучаи Get start)

                // *** End programmer edit section *** (ДоговорСтр.СтрСлучаи Get start)
                string result = this.fСтрСлучаи;
                // *** Start programmer edit section *** (ДоговорСтр.СтрСлучаи Get end)

                // *** End programmer edit section *** (ДоговорСтр.СтрСлучаи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДоговорСтр.СтрСлучаи Set start)

                // *** End programmer edit section *** (ДоговорСтр.СтрСлучаи Set start)
                this.fСтрСлучаи = value;
                // *** Start programmer edit section *** (ДоговорСтр.СтрСлучаи Set end)

                // *** End programmer edit section *** (ДоговорСтр.СтрСлучаи Set end)
            }
        }
        
        /// <summary>
        /// Договор стр.
        /// </summary>
        // *** Start programmer edit section *** (ДоговорСтр.Клиент CustomAttributes)

        // *** End programmer edit section *** (ДоговорСтр.Клиент CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент"})]
        [NotNull()]
        public virtual IIS.HHH.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (ДоговорСтр.Клиент Get start)

                // *** End programmer edit section *** (ДоговорСтр.Клиент Get start)
                IIS.HHH.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (ДоговорСтр.Клиент Get end)

                // *** End programmer edit section *** (ДоговорСтр.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДоговорСтр.Клиент Set start)

                // *** End programmer edit section *** (ДоговорСтр.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (ДоговорСтр.Клиент Set end)

                // *** End programmer edit section *** (ДоговорСтр.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Договор стр.
        /// </summary>
        // *** Start programmer edit section *** (ДоговорСтр.ПердстЭксп CustomAttributes)

        // *** End programmer edit section *** (ДоговорСтр.ПердстЭксп CustomAttributes)
        [PropertyStorage(new string[] {
                "ПердстЭксп"})]
        [NotNull()]
        public virtual IIS.HHH.ПердстЭксп ПердстЭксп
        {
            get
            {
                // *** Start programmer edit section *** (ДоговорСтр.ПердстЭксп Get start)

                // *** End programmer edit section *** (ДоговорСтр.ПердстЭксп Get start)
                IIS.HHH.ПердстЭксп result = this.fПердстЭксп;
                // *** Start programmer edit section *** (ДоговорСтр.ПердстЭксп Get end)

                // *** End programmer edit section *** (ДоговорСтр.ПердстЭксп Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДоговорСтр.ПердстЭксп Set start)

                // *** End programmer edit section *** (ДоговорСтр.ПердстЭксп Set start)
                this.fПердстЭксп = value;
                // *** Start programmer edit section *** (ДоговорСтр.ПердстЭксп Set end)

                // *** End programmer edit section *** (ДоговорСтр.ПердстЭксп Set end)
            }
        }
        
        /// <summary>
        /// Договор стр.
        /// </summary>
        // *** Start programmer edit section *** (ДоговорСтр.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ДоговорСтр.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.HHH.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ДоговорСтр.Сотрудники Get start)

                // *** End programmer edit section *** (ДоговорСтр.Сотрудники Get start)
                IIS.HHH.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ДоговорСтр.Сотрудники Get end)

                // *** End programmer edit section *** (ДоговорСтр.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДоговорСтр.Сотрудники Set start)

                // *** End programmer edit section *** (ДоговорСтр.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ДоговорСтр.Сотрудники Set end)

                // *** End programmer edit section *** (ДоговорСтр.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДоговорСтрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДоговорСтрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДоговорСтрE", typeof(IIS.HHH.ДоговорСтр));
                }
            }
            
            /// <summary>
            /// "ДоговорСтрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДоговорСтрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДоговорСтрL", typeof(IIS.HHH.ДоговорСтр));
                }
            }
        }
    }
}
