//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HHH
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заяв на стр.
    /// </summary>
    // *** Start programmer edit section *** (ЗаявНаСтр CustomAttributes)

    // *** End programmer edit section *** (ЗаявНаСтр CustomAttributes)
    [AutoAltered()]
    [Caption("Заяв на стр")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаявНаСтрE", new string[] {
            "Номер as \'Номер\'",
            "СрокСтр as \'Срок стр\'",
            "ВидСтр as \'Вид стр\'",
            "СуммаСтр as \'Сумма стр\'",
            "Дата as \'Дата\'",
            "Клиент as \'Клиент\'",
            "Клиент.ФИО as \'ФИО\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Клиент.ФИО",
            "Сотрудники.ФИО"})]
    [MasterViewDefineAttribute("ЗаявНаСтрE", "Клиент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ЗаявНаСтрE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ЗаявНаСтрL", new string[] {
            "Номер as \'Номер\'",
            "СрокСтр as \'Срок стр\'",
            "ВидСтр as \'Вид стр\'",
            "СуммаСтр as \'Сумма стр\'",
            "Дата as \'Дата\'",
            "Клиент.ФИО as \'ФИО\'",
            "Сотрудники.ФИО as \'ФИО\'"})]
    public class ЗаявНаСтр : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private int fСрокСтр;
        
        private IIS.HHH.ВидыСтр fВидСтр;
        
        private int fСуммаСтр;
        
        private System.DateTime fДата;
        
        private IIS.HHH.Клиент fКлиент;
        
        private IIS.HHH.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (ЗаявНаСтр CustomMembers)

        // *** End programmer edit section *** (ЗаявНаСтр CustomMembers)

        
        /// <summary>
        /// ВидСтр.
        /// </summary>
        // *** Start programmer edit section *** (ЗаявНаСтр.ВидСтр CustomAttributes)

        // *** End programmer edit section *** (ЗаявНаСтр.ВидСтр CustomAttributes)
        public virtual IIS.HHH.ВидыСтр ВидСтр
        {
            get
            {
                // *** Start programmer edit section *** (ЗаявНаСтр.ВидСтр Get start)

                // *** End programmer edit section *** (ЗаявНаСтр.ВидСтр Get start)
                IIS.HHH.ВидыСтр result = this.fВидСтр;
                // *** Start programmer edit section *** (ЗаявНаСтр.ВидСтр Get end)

                // *** End programmer edit section *** (ЗаявНаСтр.ВидСтр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаявНаСтр.ВидСтр Set start)

                // *** End programmer edit section *** (ЗаявНаСтр.ВидСтр Set start)
                this.fВидСтр = value;
                // *** Start programmer edit section *** (ЗаявНаСтр.ВидСтр Set end)

                // *** End programmer edit section *** (ЗаявНаСтр.ВидСтр Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ЗаявНаСтр.Дата CustomAttributes)

        // *** End programmer edit section *** (ЗаявНаСтр.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ЗаявНаСтр.Дата Get start)

                // *** End programmer edit section *** (ЗаявНаСтр.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ЗаявНаСтр.Дата Get end)

                // *** End programmer edit section *** (ЗаявНаСтр.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаявНаСтр.Дата Set start)

                // *** End programmer edit section *** (ЗаявНаСтр.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ЗаявНаСтр.Дата Set end)

                // *** End programmer edit section *** (ЗаявНаСтр.Дата Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ЗаявНаСтр.Номер CustomAttributes)

        // *** End programmer edit section *** (ЗаявНаСтр.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ЗаявНаСтр.Номер Get start)

                // *** End programmer edit section *** (ЗаявНаСтр.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ЗаявНаСтр.Номер Get end)

                // *** End programmer edit section *** (ЗаявНаСтр.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаявНаСтр.Номер Set start)

                // *** End programmer edit section *** (ЗаявНаСтр.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ЗаявНаСтр.Номер Set end)

                // *** End programmer edit section *** (ЗаявНаСтр.Номер Set end)
            }
        }
        
        /// <summary>
        /// СрокСтр.
        /// </summary>
        // *** Start programmer edit section *** (ЗаявНаСтр.СрокСтр CustomAttributes)

        // *** End programmer edit section *** (ЗаявНаСтр.СрокСтр CustomAttributes)
        public virtual int СрокСтр
        {
            get
            {
                // *** Start programmer edit section *** (ЗаявНаСтр.СрокСтр Get start)

                // *** End programmer edit section *** (ЗаявНаСтр.СрокСтр Get start)
                int result = this.fСрокСтр;
                // *** Start programmer edit section *** (ЗаявНаСтр.СрокСтр Get end)

                // *** End programmer edit section *** (ЗаявНаСтр.СрокСтр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаявНаСтр.СрокСтр Set start)

                // *** End programmer edit section *** (ЗаявНаСтр.СрокСтр Set start)
                this.fСрокСтр = value;
                // *** Start programmer edit section *** (ЗаявНаСтр.СрокСтр Set end)

                // *** End programmer edit section *** (ЗаявНаСтр.СрокСтр Set end)
            }
        }
        
        /// <summary>
        /// СуммаСтр.
        /// </summary>
        // *** Start programmer edit section *** (ЗаявНаСтр.СуммаСтр CustomAttributes)

        // *** End programmer edit section *** (ЗаявНаСтр.СуммаСтр CustomAttributes)
        public virtual int СуммаСтр
        {
            get
            {
                // *** Start programmer edit section *** (ЗаявНаСтр.СуммаСтр Get start)

                // *** End programmer edit section *** (ЗаявНаСтр.СуммаСтр Get start)
                int result = this.fСуммаСтр;
                // *** Start programmer edit section *** (ЗаявНаСтр.СуммаСтр Get end)

                // *** End programmer edit section *** (ЗаявНаСтр.СуммаСтр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаявНаСтр.СуммаСтр Set start)

                // *** End programmer edit section *** (ЗаявНаСтр.СуммаСтр Set start)
                this.fСуммаСтр = value;
                // *** Start programmer edit section *** (ЗаявНаСтр.СуммаСтр Set end)

                // *** End programmer edit section *** (ЗаявНаСтр.СуммаСтр Set end)
            }
        }
        
        /// <summary>
        /// Заяв на стр.
        /// </summary>
        // *** Start programmer edit section *** (ЗаявНаСтр.Клиент CustomAttributes)

        // *** End programmer edit section *** (ЗаявНаСтр.Клиент CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент"})]
        [NotNull()]
        public virtual IIS.HHH.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (ЗаявНаСтр.Клиент Get start)

                // *** End programmer edit section *** (ЗаявНаСтр.Клиент Get start)
                IIS.HHH.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (ЗаявНаСтр.Клиент Get end)

                // *** End programmer edit section *** (ЗаявНаСтр.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаявНаСтр.Клиент Set start)

                // *** End programmer edit section *** (ЗаявНаСтр.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (ЗаявНаСтр.Клиент Set end)

                // *** End programmer edit section *** (ЗаявНаСтр.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Заяв на стр.
        /// </summary>
        // *** Start programmer edit section *** (ЗаявНаСтр.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ЗаявНаСтр.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.HHH.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ЗаявНаСтр.Сотрудники Get start)

                // *** End programmer edit section *** (ЗаявНаСтр.Сотрудники Get start)
                IIS.HHH.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ЗаявНаСтр.Сотрудники Get end)

                // *** End programmer edit section *** (ЗаявНаСтр.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаявНаСтр.Сотрудники Set start)

                // *** End programmer edit section *** (ЗаявНаСтр.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ЗаявНаСтр.Сотрудники Set end)

                // *** End programmer edit section *** (ЗаявНаСтр.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаявНаСтрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявНаСтрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявНаСтрE", typeof(IIS.HHH.ЗаявНаСтр));
                }
            }
            
            /// <summary>
            /// "ЗаявНаСтрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявНаСтрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявНаСтрL", typeof(IIS.HHH.ЗаявНаСтр));
                }
            }
        }
    }
}
