//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HHH
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиент.
    /// </summary>
    // *** Start programmer edit section *** (Клиент CustomAttributes)

    // *** End programmer edit section *** (Клиент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиентE", new string[] {
            "ФИО as \'ФИО\'",
            "Адрес as \'Адрес\'",
            "НомерПас as \'Номер пас\'",
            "СерияПас as \'Серия пас\'",
            "Телефон as \'Телефон\'",
            "ИНН as \'ИНН\'"})]
    [View("КлиентL", new string[] {
            "ФИО as \'ФИО\'",
            "Адрес as \'Адрес\'",
            "НомерПас as \'Номер пас\'",
            "СерияПас as \'Серия пас\'",
            "Телефон as \'Телефон\'",
            "ИНН as \'ИНН\'"})]
    public class Клиент : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private string fАдрес;
        
        private int fНомерПас;
        
        private int fСерияПас;
        
        private int fТелефон;
        
        private int fИНН;
        
        // *** Start programmer edit section *** (Клиент CustomMembers)

        // *** End programmer edit section *** (Клиент CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Адрес CustomAttributes)

        // *** End programmer edit section *** (Клиент.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Адрес Get start)

                // *** End programmer edit section *** (Клиент.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Клиент.Адрес Get end)

                // *** End programmer edit section *** (Клиент.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Адрес Set start)

                // *** End programmer edit section *** (Клиент.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Клиент.Адрес Set end)

                // *** End programmer edit section *** (Клиент.Адрес Set end)
            }
        }
        
        /// <summary>
        /// ИНН.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.ИНН CustomAttributes)

        // *** End programmer edit section *** (Клиент.ИНН CustomAttributes)
        public virtual int ИНН
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.ИНН Get start)

                // *** End programmer edit section *** (Клиент.ИНН Get start)
                int result = this.fИНН;
                // *** Start programmer edit section *** (Клиент.ИНН Get end)

                // *** End programmer edit section *** (Клиент.ИНН Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.ИНН Set start)

                // *** End programmer edit section *** (Клиент.ИНН Set start)
                this.fИНН = value;
                // *** Start programmer edit section *** (Клиент.ИНН Set end)

                // *** End programmer edit section *** (Клиент.ИНН Set end)
            }
        }
        
        /// <summary>
        /// НомерПас.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.НомерПас CustomAttributes)

        // *** End programmer edit section *** (Клиент.НомерПас CustomAttributes)
        public virtual int НомерПас
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.НомерПас Get start)

                // *** End programmer edit section *** (Клиент.НомерПас Get start)
                int result = this.fНомерПас;
                // *** Start programmer edit section *** (Клиент.НомерПас Get end)

                // *** End programmer edit section *** (Клиент.НомерПас Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.НомерПас Set start)

                // *** End programmer edit section *** (Клиент.НомерПас Set start)
                this.fНомерПас = value;
                // *** Start programmer edit section *** (Клиент.НомерПас Set end)

                // *** End programmer edit section *** (Клиент.НомерПас Set end)
            }
        }
        
        /// <summary>
        /// СерияПас.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.СерияПас CustomAttributes)

        // *** End programmer edit section *** (Клиент.СерияПас CustomAttributes)
        public virtual int СерияПас
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.СерияПас Get start)

                // *** End programmer edit section *** (Клиент.СерияПас Get start)
                int result = this.fСерияПас;
                // *** Start programmer edit section *** (Клиент.СерияПас Get end)

                // *** End programmer edit section *** (Клиент.СерияПас Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.СерияПас Set start)

                // *** End programmer edit section *** (Клиент.СерияПас Set start)
                this.fСерияПас = value;
                // *** Start programmer edit section *** (Клиент.СерияПас Set end)

                // *** End programmer edit section *** (Клиент.СерияПас Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Телефон CustomAttributes)

        // *** End programmer edit section *** (Клиент.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Телефон Get start)

                // *** End programmer edit section *** (Клиент.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (Клиент.Телефон Get end)

                // *** End programmer edit section *** (Клиент.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Телефон Set start)

                // *** End programmer edit section *** (Клиент.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Клиент.Телефон Set end)

                // *** End programmer edit section *** (Клиент.Телефон Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.ФИО CustomAttributes)

        // *** End programmer edit section *** (Клиент.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.ФИО Get start)

                // *** End programmer edit section *** (Клиент.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Клиент.ФИО Get end)

                // *** End programmer edit section *** (Клиент.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.ФИО Set start)

                // *** End programmer edit section *** (Клиент.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Клиент.ФИО Set end)

                // *** End programmer edit section *** (Клиент.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентE", typeof(IIS.HHH.Клиент));
                }
            }
            
            /// <summary>
            /// "КлиентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентL", typeof(IIS.HHH.Клиент));
                }
            }
        }
    }
}
