//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HHH
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Пердст эксп.
    /// </summary>
    // *** Start programmer edit section *** (ПердстЭксп CustomAttributes)

    // *** End programmer edit section *** (ПердстЭксп CustomAttributes)
    [AutoAltered()]
    [Caption("Пердст эксп")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПердстЭкспE", new string[] {
            "ОсновПровед as \'Основ провед\'",
            "Дата as \'Дата\'",
            "ВидЭксп as \'Вид эксп\'",
            "РезулЭксп as \'Резул эксп\'",
            "ЦельЭксп as \'Цель эксп\'",
            "ОбъектЭксп as \'Объект эксп\'",
            "Номер as \'Номер\'",
            "ЗаявНаСтр as \'Заяв на стр\'",
            "ЗаявНаСтр.Номер as \'Номер\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "Клиент as \'Клиент\'",
            "Клиент.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "ЗаявНаСтр.Номер",
            "Сотрудники.ФИО",
            "Клиент.ФИО"})]
    [MasterViewDefineAttribute("ПердстЭкспE", "ЗаявНаСтр", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [MasterViewDefineAttribute("ПердстЭкспE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ПердстЭкспE", "Клиент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ПердстЭкспL", new string[] {
            "ОсновПровед as \'Основ провед\'",
            "Дата as \'Дата\'",
            "ВидЭксп as \'Вид эксп\'",
            "РезулЭксп as \'Резул эксп\'",
            "ЦельЭксп as \'Цель эксп\'",
            "ОбъектЭксп as \'Объект эксп\'",
            "Номер as \'Номер\'",
            "ЗаявНаСтр.Номер as \'Номер\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "Клиент.ФИО as \'ФИО\'"})]
    public class ПердстЭксп : ICSSoft.STORMNET.DataObject
    {
        
        private string fОсновПровед;
        
        private System.DateTime fДата;
        
        private string fВидЭксп;
        
        private IIS.HHH.РезЭксп fРезулЭксп;
        
        private string fЦельЭксп;
        
        private string fОбъектЭксп;
        
        private int fНомер;
        
        private IIS.HHH.ЗаявНаСтр fЗаявНаСтр;
        
        private IIS.HHH.Сотрудники fСотрудники;
        
        private IIS.HHH.Клиент fКлиент;
        
        // *** Start programmer edit section *** (ПердстЭксп CustomMembers)

        // *** End programmer edit section *** (ПердстЭксп CustomMembers)

        
        /// <summary>
        /// ВидЭксп.
        /// </summary>
        // *** Start programmer edit section *** (ПердстЭксп.ВидЭксп CustomAttributes)

        // *** End programmer edit section *** (ПердстЭксп.ВидЭксп CustomAttributes)
        [StrLen(255)]
        public virtual string ВидЭксп
        {
            get
            {
                // *** Start programmer edit section *** (ПердстЭксп.ВидЭксп Get start)

                // *** End programmer edit section *** (ПердстЭксп.ВидЭксп Get start)
                string result = this.fВидЭксп;
                // *** Start programmer edit section *** (ПердстЭксп.ВидЭксп Get end)

                // *** End programmer edit section *** (ПердстЭксп.ВидЭксп Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПердстЭксп.ВидЭксп Set start)

                // *** End programmer edit section *** (ПердстЭксп.ВидЭксп Set start)
                this.fВидЭксп = value;
                // *** Start programmer edit section *** (ПердстЭксп.ВидЭксп Set end)

                // *** End programmer edit section *** (ПердстЭксп.ВидЭксп Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ПердстЭксп.Дата CustomAttributes)

        // *** End programmer edit section *** (ПердстЭксп.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ПердстЭксп.Дата Get start)

                // *** End programmer edit section *** (ПердстЭксп.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ПердстЭксп.Дата Get end)

                // *** End programmer edit section *** (ПердстЭксп.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПердстЭксп.Дата Set start)

                // *** End programmer edit section *** (ПердстЭксп.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ПердстЭксп.Дата Set end)

                // *** End programmer edit section *** (ПердстЭксп.Дата Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ПердстЭксп.Номер CustomAttributes)

        // *** End programmer edit section *** (ПердстЭксп.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ПердстЭксп.Номер Get start)

                // *** End programmer edit section *** (ПердстЭксп.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ПердстЭксп.Номер Get end)

                // *** End programmer edit section *** (ПердстЭксп.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПердстЭксп.Номер Set start)

                // *** End programmer edit section *** (ПердстЭксп.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ПердстЭксп.Номер Set end)

                // *** End programmer edit section *** (ПердстЭксп.Номер Set end)
            }
        }
        
        /// <summary>
        /// ОбъектЭксп.
        /// </summary>
        // *** Start programmer edit section *** (ПердстЭксп.ОбъектЭксп CustomAttributes)

        // *** End programmer edit section *** (ПердстЭксп.ОбъектЭксп CustomAttributes)
        [StrLen(255)]
        public virtual string ОбъектЭксп
        {
            get
            {
                // *** Start programmer edit section *** (ПердстЭксп.ОбъектЭксп Get start)

                // *** End programmer edit section *** (ПердстЭксп.ОбъектЭксп Get start)
                string result = this.fОбъектЭксп;
                // *** Start programmer edit section *** (ПердстЭксп.ОбъектЭксп Get end)

                // *** End programmer edit section *** (ПердстЭксп.ОбъектЭксп Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПердстЭксп.ОбъектЭксп Set start)

                // *** End programmer edit section *** (ПердстЭксп.ОбъектЭксп Set start)
                this.fОбъектЭксп = value;
                // *** Start programmer edit section *** (ПердстЭксп.ОбъектЭксп Set end)

                // *** End programmer edit section *** (ПердстЭксп.ОбъектЭксп Set end)
            }
        }
        
        /// <summary>
        /// ОсновПровед.
        /// </summary>
        // *** Start programmer edit section *** (ПердстЭксп.ОсновПровед CustomAttributes)

        // *** End programmer edit section *** (ПердстЭксп.ОсновПровед CustomAttributes)
        [StrLen(255)]
        public virtual string ОсновПровед
        {
            get
            {
                // *** Start programmer edit section *** (ПердстЭксп.ОсновПровед Get start)

                // *** End programmer edit section *** (ПердстЭксп.ОсновПровед Get start)
                string result = this.fОсновПровед;
                // *** Start programmer edit section *** (ПердстЭксп.ОсновПровед Get end)

                // *** End programmer edit section *** (ПердстЭксп.ОсновПровед Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПердстЭксп.ОсновПровед Set start)

                // *** End programmer edit section *** (ПердстЭксп.ОсновПровед Set start)
                this.fОсновПровед = value;
                // *** Start programmer edit section *** (ПердстЭксп.ОсновПровед Set end)

                // *** End programmer edit section *** (ПердстЭксп.ОсновПровед Set end)
            }
        }
        
        /// <summary>
        /// РезулЭксп.
        /// </summary>
        // *** Start programmer edit section *** (ПердстЭксп.РезулЭксп CustomAttributes)

        // *** End programmer edit section *** (ПердстЭксп.РезулЭксп CustomAttributes)
        public virtual IIS.HHH.РезЭксп РезулЭксп
        {
            get
            {
                // *** Start programmer edit section *** (ПердстЭксп.РезулЭксп Get start)

                // *** End programmer edit section *** (ПердстЭксп.РезулЭксп Get start)
                IIS.HHH.РезЭксп result = this.fРезулЭксп;
                // *** Start programmer edit section *** (ПердстЭксп.РезулЭксп Get end)

                // *** End programmer edit section *** (ПердстЭксп.РезулЭксп Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПердстЭксп.РезулЭксп Set start)

                // *** End programmer edit section *** (ПердстЭксп.РезулЭксп Set start)
                this.fРезулЭксп = value;
                // *** Start programmer edit section *** (ПердстЭксп.РезулЭксп Set end)

                // *** End programmer edit section *** (ПердстЭксп.РезулЭксп Set end)
            }
        }
        
        /// <summary>
        /// ЦельЭксп.
        /// </summary>
        // *** Start programmer edit section *** (ПердстЭксп.ЦельЭксп CustomAttributes)

        // *** End programmer edit section *** (ПердстЭксп.ЦельЭксп CustomAttributes)
        [StrLen(255)]
        public virtual string ЦельЭксп
        {
            get
            {
                // *** Start programmer edit section *** (ПердстЭксп.ЦельЭксп Get start)

                // *** End programmer edit section *** (ПердстЭксп.ЦельЭксп Get start)
                string result = this.fЦельЭксп;
                // *** Start programmer edit section *** (ПердстЭксп.ЦельЭксп Get end)

                // *** End programmer edit section *** (ПердстЭксп.ЦельЭксп Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПердстЭксп.ЦельЭксп Set start)

                // *** End programmer edit section *** (ПердстЭксп.ЦельЭксп Set start)
                this.fЦельЭксп = value;
                // *** Start programmer edit section *** (ПердстЭксп.ЦельЭксп Set end)

                // *** End programmer edit section *** (ПердстЭксп.ЦельЭксп Set end)
            }
        }
        
        /// <summary>
        /// Пердст эксп.
        /// </summary>
        // *** Start programmer edit section *** (ПердстЭксп.ЗаявНаСтр CustomAttributes)

        // *** End programmer edit section *** (ПердстЭксп.ЗаявНаСтр CustomAttributes)
        [PropertyStorage(new string[] {
                "ЗаявНаСтр"})]
        [NotNull()]
        public virtual IIS.HHH.ЗаявНаСтр ЗаявНаСтр
        {
            get
            {
                // *** Start programmer edit section *** (ПердстЭксп.ЗаявНаСтр Get start)

                // *** End programmer edit section *** (ПердстЭксп.ЗаявНаСтр Get start)
                IIS.HHH.ЗаявНаСтр result = this.fЗаявНаСтр;
                // *** Start programmer edit section *** (ПердстЭксп.ЗаявНаСтр Get end)

                // *** End programmer edit section *** (ПердстЭксп.ЗаявНаСтр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПердстЭксп.ЗаявНаСтр Set start)

                // *** End programmer edit section *** (ПердстЭксп.ЗаявНаСтр Set start)
                this.fЗаявНаСтр = value;
                // *** Start programmer edit section *** (ПердстЭксп.ЗаявНаСтр Set end)

                // *** End programmer edit section *** (ПердстЭксп.ЗаявНаСтр Set end)
            }
        }
        
        /// <summary>
        /// Пердст эксп.
        /// </summary>
        // *** Start programmer edit section *** (ПердстЭксп.Клиент CustomAttributes)

        // *** End programmer edit section *** (ПердстЭксп.Клиент CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент"})]
        [NotNull()]
        public virtual IIS.HHH.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (ПердстЭксп.Клиент Get start)

                // *** End programmer edit section *** (ПердстЭксп.Клиент Get start)
                IIS.HHH.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (ПердстЭксп.Клиент Get end)

                // *** End programmer edit section *** (ПердстЭксп.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПердстЭксп.Клиент Set start)

                // *** End programmer edit section *** (ПердстЭксп.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (ПердстЭксп.Клиент Set end)

                // *** End programmer edit section *** (ПердстЭксп.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Пердст эксп.
        /// </summary>
        // *** Start programmer edit section *** (ПердстЭксп.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ПердстЭксп.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.HHH.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ПердстЭксп.Сотрудники Get start)

                // *** End programmer edit section *** (ПердстЭксп.Сотрудники Get start)
                IIS.HHH.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ПердстЭксп.Сотрудники Get end)

                // *** End programmer edit section *** (ПердстЭксп.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПердстЭксп.Сотрудники Set start)

                // *** End programmer edit section *** (ПердстЭксп.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ПердстЭксп.Сотрудники Set end)

                // *** End programmer edit section *** (ПердстЭксп.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПердстЭкспE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПердстЭкспE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПердстЭкспE", typeof(IIS.HHH.ПердстЭксп));
                }
            }
            
            /// <summary>
            /// "ПердстЭкспL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПердстЭкспL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПердстЭкспL", typeof(IIS.HHH.ПердстЭксп));
                }
            }
        }
    }
}
